// Generated by CoffeeScript 1.8.0
(function() {
  this.Spacer = (function() {
    var onWindowLoad, print, replaceAll, spaceInputContent, spacer;

    function Spacer() {}

    print = function(text) {
      return console.log(text);
    };

    replaceAll = function(text, search, replacement) {
      return text.split(search).join(replacement);
    };

    spacer = function(textForSpacer) {
      var letter, resultString, upperText, _i, _len;
      upperText = textForSpacer.toUpperCase();
      resultString = [];
      for (_i = 0, _len = upperText.length; _i < _len; _i++) {
        letter = upperText[_i];
        resultString.push(letter);
      }
      resultString = resultString.toString();
      return replaceAll(resultString, ",", " ");
    };

    spaceInputContent = function() {
      var inputElement, outputDiv, spacedText;
      inputElement = document.getElementById("not-spaced");
      spacedText = spacer(inputElement.value);
      outputDiv = document.getElementById("spaced");
      return outputDiv.innerHTML = spacer(spacedText);
    };

    onWindowLoad = function() {
      var inputElement, outputDiv, spacedText;
      inputElement = document.getElementById("not-spaced");
      spacedText = spacer(inputElement.value);
      outputDiv = document.getElementById("spaced");
      return outputDiv.innerHTML = spacedText;
    };

    window.spaceInputContent = spaceInputContent;

    window.onload = onWindowLoad;

    return Spacer;

  })();

}).call(this);
